export const GUIDELINE_FETCH = "GUIDELINE_FETCH";
export const GUIDELINE_FETCH_RECEIVED = "GUIDELINE_FETCH_RECEIVED";
export const GUIDELINE_FETCH_DETAIL = "GUIDELINE_FETCH_DETAIL";
export const GUIDELINE_FETCH_DETAIL_RECEIVED =
  "GUIDELINE_FETCH_DETAIL_RECEIVED";
export const GUIDELINE_POST = "GUIDELINE_POST";
export const GUIDELINE_PUT = "GUIDELINE_PUT";
export const GUIDELINE_DELETE = "GUIDELINE_DELETE";
export const ON_GUIDELINE_SELECTED = "ON_GUIDELINE_SELECTED";

export const NODE_NAV_TURN = "NODE_NAV_TURN";

export const GUIDE_NODE_FETCH = "GUIDE_NODE_FETCH";
export const GUIDE_NODE_FETCH_RECEIVED = "GUIDE_NODE_FETCH_RECEIVED";
export const GUIDE_NODE_INSERT_RECEIVED = "GUIDE_NODE_INSERT_RECEIVED";
export const GUIDE_NODE_POST = "GUIDE_NODE_POST";
export const GUIDE_NODE_PUT = "GUIDE_NODE_PUT";
export const GUIDE_NODE_LOCATION_PUT = "GUIDE_NODE_LOCATION_PUT";
export const GUIDE_NODE_DELETE = "GUIDE_NODE_DELETE";
export const GUIDE_NODE_INSERT_RESET = "GUIDE_NODE_INSERT_RESET";

export const GUIDE_NODE_CONTENT_FETCH_DETAIL =
  "GUIDE_NODE_CONTENT_FETCH_DETAIL";
export const GUIDE_NODE_CONTENT_FETCH_DETAIL_RECEIVED =
  "GUIDE_NODE_CONTENT_FETCH_DETAIL_RECEIVED";
export const GUIDE_NODE_CONTENT_POST = "GUIDE_NODE_CONTENT_POST";
export const GUIDE_NODE_CONTENT_PUT = "GUIDE_NODE_CONTENT_PUT";
export const GUIDE_NODE_CONTENT_CHECKED_NODE =
  "GUIDE_NODE_CONTENT_CHECKED_NODE";
