//  Login Watcher Actions
export const LOG_IN_WATCHER = "LOG_IN_WATCHER";
export const LOG_OUT_WATCHER = "LOG_OUT_WATCHER";
export const GET_USER_PROFILE_WATCHER = "GET_USER_PROFILE_WATCHER";
// Login Reducer Actions
export const FILL_USER_PROFILE = "FILL_USER_PROFILE";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_SESSION = "CLEAR_SESSION";

export const APP_ON_FORM_DIRTY = "APP_ON_FORM_DIRTY";
export const APP_FETCH_USER = "APP_FETCH_USER";
export const APP_FETCH_USER_RECEIVED = "APP_FETCH_USER_RECEIVED";
export const APP_ENQUEUE_SNACKBAR = "APP_ENQUEUE_SNACKBAR";
export const APP_CLOSE_SNACKBAR = "APP_CLOSE_SNACKBAR";
export const APP_REMOVE_SNACKBAR = "APP_REMOVE_SNACKBAR";
export const APP_LOADING_INCREASE = "APP_LOADING_INCREASE";
export const APP_LOADING_DECREASE = "APP_LOADING_DECREASE";
export const APP_FINISH_SAVING_DATA = "APP_FINISH_SAVING_DATA";

export const CHILDREN_FETCH = "CHILDREN_FETCH";
export const CHILDREN_FETCH_RECEIVED = "CHILDREN_FETCH_RECEIVED";
export const CHILDREN_FETCH_ALL = "CHILDREN_FETCH_ALL";
export const CHILDREN_FETCH_ALL_RECEIVED = "CHILDREN_FETCH_ALL_RECEIVED";
export const CHILDREN_FETCH_DETAIL = "CHILDREN_FETCH_DETAIL";
export const CHILDREN_FETCH_DETAIL_RECEIVED = "CHILDREN_FETCH_DETAIL_RECEIVED";
export const CHILDREN_POST = "CHILDREN_POST";
export const CHILDREN_PUT = "CHILDREN_PUT";
export const CHILDREN_DELETE = "CHILDREN_DELETE";
export const CHILDREN_POST_PHOTO = "CHILDREN_POST_PHOTO";

export const GUIDELINE_FETCH = "GUIDELINE_FETCH";
export const GUIDELINE_FETCH_RECEIVED = "GUIDELINE_FETCH_RECEIVED";
export const GUIDELINE_FETCH_DETAIL = "GUIDELINE_FETCH_DETAIL";
export const GUIDELINE_FETCH_DETAIL_RECEIVED =
  "GUIDELINE_FETCH_DETAIL_RECEIVED";
export const GUIDELINE_POST = "GUIDELINE_POST";
export const GUIDELINE_PUT = "GUIDELINE_PUT";
export const GUIDELINE_DELETE = "GUIDELINE_DELETE";
export const ON_GUIDELINE_SELECTED = "ON_GUIDELINE_SELECTED";

export const MEAL_FETCH = "MEAL_FETCH";
export const MEAL_FETCH_RECEIVED = "MEAL_FETCH_RECEIVED";
export const MEAL_FETCH_DETAIL = "MEAL_FETCH_DETAIL";
export const MEAL_FETCH_DETAIL_RECEIVED = "MEAL_FETCH_DETAIL_RECEIVED";
export const MEAL_POST = "MEAL_POST";
export const MEAL_PUT = "MEAL_PUT";
export const MEAL_DELETE = "MEAL_DELETE";

export const MENU_FETCH = "MENU_FETCH";
export const MENU_FETCH_RECEIVED = "MENU_FETCH_RECEIVED";
export const MENU_FETCH_DETAIL = "MENU_FETCH_DETAIL";
export const MENU_FETCH_DETAIL_RECEIVED = "MENU_FETCH_DETAIL_RECEIVED";
export const MENU_POST = "MENU_POST";
export const MENU_PUT = "MENU_PUT";
export const MENU_DELETE = "MENU_DELETE";
export const MENU_POST_PHOTO = "MENU_POST_PHOTO";
export const MENU_ON_SAVE_CLICKED = "MENU_ON_SAVE_CLICKED";
export const MENU_ON_PUT_GUIDELINES = "MENU_ON_PUT_GUIDELINES";

export const GUIDE_NODE_FETCH = "GUIDE_NODE_FETCH";
export const GUIDE_NODE_FETCH_RECEIVED = "GUIDE_NODE_FETCH_RECEIVED";
export const GUIDE_NODE_INSERT_RECEIVED = "GUIDE_NODE_INSERT_RECEIVED";
export const GUIDE_NODE_POST = "GUIDE_NODE_POST";
export const GUIDE_NODE_PUT = "GUIDE_NODE_PUT";
export const GUIDE_NODE_DELETE = "GUIDE_NODE_DELETE";
export const GUIDE_NODE_INSERT_RESET = "GUIDE_NODE_INSERT_RESET";
