//  Login Watcher Actions
export const LOG_IN_WATCHER = "LOG_IN_WATCHER";
export const LOG_OUT_WATCHER = "LOG_OUT_WATCHER";
export const GET_USER_PROFILE_WATCHER = "GET_USER_PROFILE_WATCHER";
// Login Reducer Actions
export const FILL_USER_PROFILE = "FILL_USER_PROFILE";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_SESSION = "CLEAR_SESSION";

export const APP_ON_FORM_DIRTY = "APP_ON_FORM_DIRTY";
export const APP_FETCH_USER = "APP_FETCH_USER";
export const APP_FETCH_USER_RECEIVED = "APP_FETCH_USER_RECEIVED";
export const APP_ENQUEUE_SNACKBAR = "APP_ENQUEUE_SNACKBAR";
export const APP_CLOSE_SNACKBAR = "APP_CLOSE_SNACKBAR";
export const APP_REMOVE_SNACKBAR = "APP_REMOVE_SNACKBAR";
export const APP_LOADING_INCREASE = "APP_LOADING_INCREASE";
export const APP_LOADING_DECREASE = "APP_LOADING_DECREASE";
export const APP_FINISH_SAVING_DATA = "APP_FINISH_SAVING_DATA";

export const GUIDELINE_FETCH = "GUIDELINE_FETCH";
export const GUIDELINE_FETCH_RECEIVED = "GUIDELINE_FETCH_RECEIVED";
export const GUIDELINE_FETCH_DETAIL = "GUIDELINE_FETCH_DETAIL";
export const GUIDELINE_FETCH_DETAIL_RECEIVED =
  "GUIDELINE_FETCH_DETAIL_RECEIVED";
export const GUIDELINE_POST = "GUIDELINE_POST";
export const GUIDELINE_PUT = "GUIDELINE_PUT";
export const GUIDELINE_DELETE = "GUIDELINE_DELETE";
export const ON_GUIDELINE_SELECTED = "ON_GUIDELINE_SELECTED";

export const NODE_NAV_TURN = "NODE_NAV_TURN";

export const GUIDE_NODE_FETCH = "GUIDE_NODE_FETCH";
export const GUIDE_NODE_FETCH_RECEIVED = "GUIDE_NODE_FETCH_RECEIVED";
export const GUIDE_NODE_INSERT_RECEIVED = "GUIDE_NODE_INSERT_RECEIVED";
export const GUIDE_NODE_POST = "GUIDE_NODE_POST";
export const GUIDE_NODE_PUT = "GUIDE_NODE_PUT";
export const GUIDE_NODE_DELETE = "GUIDE_NODE_DELETE";
export const GUIDE_NODE_INSERT_RESET = "GUIDE_NODE_INSERT_RESET";

export const GUIDE_NODE_CONTENT_FETCH_DETAIL =
  "GUIDE_NODE_CONTENT_FETCH_DETAIL";
export const GUIDE_NODE_CONTENT_FETCH_DETAIL_RECEIVED =
  "GUIDE_NODE_CONTENT_FETCH_DETAIL_RECEIVED";
export const GUIDE_NODE_CONTENT_POST = "GUIDE_NODE_CONTENT_POST";
export const GUIDE_NODE_CONTENT_PUT = "GUIDE_NODE_CONTENT_PUT";
export const GUIDE_NODE_CONTENT_CHECKED_NODE =
  "GUIDE_NODE_CONTENT_CHECKED_NODE";
